### ISSUE TITLE
Find Out the Actionable Goals of the Lab this Quarter and Make Plans for them

### ISSUE THREAD

**Issue by NatRamya** [Carceral-Ecologies/lab_book#2]
-[ ] What are the Goals?
So far I know we want to finish the manual coding, what else? What's our stake in the OSHA data analysis? What are our project management goals?

**Comment by shapironick** [comment]
do goals need to be achievable in the quarter? 

OSHA- we need to understand the scope and coverage of the data set, validate and begin data analysis

Project Management-- establish and document systems for generating and assigning tasks, create infrastructure that doesn't need to be built and re-built each quarter. get students working in a way that is not too much and not too little. map out how communication should go so people know who to contact about what. review and advance protocol.  (more detail on project management because its not included elsewhere)

**Comment by NatRamya** [comment]
copied all comments over to Issue #1, closing this issue
